language: java
jdk:
  - openjdk11

dist: "focal"
arch: amd64

branches: # 1.
  only:
    - dev

cache: # 2.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build bootJar -x Test" # 3.

notifications: # 4.
  email:
    recipients:
      - penekhun@gmail.com


before_install:
  #  gradle 버전 변경
  - sudo wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
  - sudo unzip -qq gradle-7.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-7.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -version
  - gradle wrap
  - chmod +x ./gradlew  # gradlew 실행 권한 부여 */

before_deploy:
  - mkdir -p before_deploy
  - mkdir -p real-deploy
  - cp build/libs/*.jar before_deploy/
  - cp appspec.yml before_deploy/
  - cp DeployScript.sh before_deploy/
  - cd before_deploy
  - zip -r before_deploy * && cd ../
  - mv before_deploy/before_deploy.zip real-deploy/shortUrl.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: seonghun-shorturl-bucket-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: real-deploy
    wait-until-deployed: true
    on:
      all_branches: true #마스터가 아닌 브런치도 deploy할 수 있게