language: java
jdk:
  - openjdk11

dist: focal

os: linux
arch: amd64

branches: # 1.
  only:
    - dev
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x Test" # 3.

notifications: # 4.
  email:
    recipients:
      - penekhun@gmail.com


before_install:
  - chmod +x ./gradlew  # gradlew 실행 권한 부여 */

before_deploy:
  - mkdir -p before_deploy
  - mkdir -p real-deploy
  - cp -r build/ before_deploy/
  - ls before_deploy
  - cp appspec.yml before_deploy/
  - cp initRun.sh before_deploy/
  - cd before_deploy
  - zip -r before_deploy * && cd ../
  - mv before_deploy/before_deploy.zip real-deploy/shortUrl.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: seonghun-shorturl-bucket-build
    region: ap-northeast-2
    acl: private
    skip_cleanup: true
    local_dir: real-deploy
    wait-until-deployed: true
    on:
      all_branches: true #마스터가 아닌 브런치도 deploy할 수 있게